services:
  api:
    build:
      context: ./api
      dockerfile: ../containers/api/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN}
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: ./app
      dockerfile: ../containers/app/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=${NODE_ENV}
      - VITE_API_TARGET=http://api:3000
    depends_on:
      - api

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata: